all:
	gcc -g -c -Wall _programas_de_transposicion.c -o  _programas_de_transposicion.o
	gcc -g -Wall _programas_de_transposicion.o  -o _programas_de_transposicion 
	
clean:
	rm *.o
	rm _programas_de_transposicion